---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ambassador-monitor
  namespace: ambassador
  labels:
    release: kube-prometheus-1608759028
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      service: ambassador-admin
  endpoints:
  - port: ambassador-admin
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pepper-poker-monitor
  namespace: poker
  labels:
    release: kube-prometheus-1608759028
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      service: pepper-poker-http-service
  endpoints:
  - port: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: linkerd-prometheus
    # release: monitoring
    release: kube-prometheus-1608759028
  name: linkerd-federate
  namespace: linkerd
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    params:
      match[]:
      - '{job="linkerd-proxy"}'
      - '{job="linkerd-controller"}'
    path: /federate
    port: admin-http
    honorLabels: true
    relabelings:
    - action: keep
      regex: '^prometheus$'
      sourceLabels:
      - '__meta_kubernetes_pod_container_name'
  jobLabel: app
  namespaceSelector:
    matchNames:
    - linkerd
  selector:
    matchLabels:
      linkerd.io/control-plane-component: prometheus
# keycloak in the helm chart
