---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pepper-poker-monitor
  namespace: poker
  labels:
    release: kube-prometheus-1608759028
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      service: pepper-poker-http-service
  endpoints:
  - port: http
