---
apiVersion: v1
kind: Namespace
metadata:
  name: poker
  annotations:
    linkerd.io/inject: enabled
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: monitoring
#   annotations:
#     linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ambassador
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  annotations:
    linkerd.io/inject: enabled





