apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"grpc": "HTTP2"}'
    cloud.google.com/backend-config: '{"default": "pepper-poker-grpc-hc-config"}'
  name: pepper-poker-grpc-service
  namespace: poker
  labels:
    name: pepper-poker-grpc-service
spec:
  ports:
    - port: 8443
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: pepper-poker
  type: NodePort
  # type: LoadBalancer
  # clusterIP: None # headless service
