apiVersion: v1
kind: Service
metadata:
  name: pepper-poker-grpc-service
  namespace: poker
  labels:
    name: pepper-poker-grpc-service
spec:
  ports:
    - port: 8443 # no targetPort for headless service
      # targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: pepper-poker
  type: ClusterIP
  clusterIP: None # headless service

