---
bases:
  - ../../base
patchesStrategicMerge:
  - set_memory.yaml
patchesJson6902:
  - target:
      name: pepper-poker
      kind: Deployment
      version: v1
      group: apps
    path: patch.yaml
