apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepper-poker
  namespace: poker
spec:
  template:
    spec:
      containers:
        - name: pepper-poker
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
